apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operators
  labels:
    group: applications
spec:
  generators:
  - list:
      elements:
        - name: mq
          namespace: mq
        - name: openshift-cert-manager
          namespace: cert-manager-operator 
        - name: cert-utils
          namespace: cert-utils-operator 
  template:
    metadata:
      name: '{{name}}-operator'
      labels:
        group: applications
      annotations:
        argocd.argoproj.io/sync-wave: "100"
    spec:
      project: operators
      source:
        path: 'components/{{name}}/operator'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
