apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Generate these config maps from mqsc files to support
# syntax hignlighting in tooling.
configMapGenerator:
  - name: native-ha-qm-configmap
    files:
      - qm-config/config.mqsc
      - qm-config/mq.ini

generatorOptions:
  disableNameSuffixHash: true

resources: 

  - tls/ca-ss-issuer.yaml
  - tls/nativeha-certificate.yaml
  - tls/mq-server-certificate.yaml

  - qm.yaml

  - mqwebuser-secret.yaml
