apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mq-server-certificate
spec:
  dnsNames:
    - 'native-ha-qm-ibm-mq-qm-mq.apps.6655838ccc225c001d4ee9d4.cloud.techzone.ibm.com'
    - 'native-ha-qm-ibm-mq-web-mq.apps.6655838ccc225c001d4ee9d4.cloud.techzone.ibm.com'