apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operands
  labels:
    group: applications
spec:
  generators:
  - list:
      elements:
        - name: mq
          namespace: mq
          sync-wave: "200"
        - name: reloader
          namespace: mq
          sync-wave: "200"
        
  template:
    metadata:
      name: '{{name}}'
      labels:
        group: applications
      annotations:
        argocd.argoproj.io/sync-wave: '{{sync-wave}}'
    spec:
      project: operands
      source:
        path: 'envs/azure/nonprod/{{name}}/'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true