apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: storage-class.yaml
    target:
      name: native-ha-qm
      kind: QueueManager
  - path: storage-class-singleinstance.yaml
    target:
      name: singleinstance-qm
      kind: QueueManager
  - path: mq-cert-domain.yaml
    target:
      kind: Certificate
      name: mq-server-certificate
  - path: mq-cert-domain-si.yaml
    target:
      kind: Certificate
      name: mq-single-instance-server-certificate


      