apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mq-server-certificate
spec:
  dnsNames:
    - 'native-ha-qm-ibm-mq-qm-mq.apps.g7pphpyh.eastus.aroapp.io'
    - 'native-ha-qm-ibm-mq-web-mq.apps.g7pphpyh.eastus.aroapp.io'