apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: native-ha-qm
spec:
  queueManager:
    storage:
      queueManager:
        class: managed-csi
      persistedData:
        class: managed-csi
      recoveryLogs:
        class: managed-csi
